# Generated by Django 5.2.11 on 2026-02-24 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Book Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReadingLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='reading.bookcategory')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PronunciationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected', models.TextField()),
                ('spoken', models.TextField()),
                ('score', models.FloatField(blank=True, null=True)),
                ('mispronounced', models.JSONField(blank=True, default=list)),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pron_attempts', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pron_attempts', to='reading.readinglesson')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='reading.book')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='readinglesson',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='reading.unit'),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.UniqueConstraint(fields=('category', 'order'), name='unique_book_order_per_category'),
        ),
        migrations.AddIndex(
            model_name='pronunciationattempt',
            index=models.Index(fields=['lesson', 'created_at'], name='reading_pro_lesson__865b81_idx'),
        ),
        migrations.AddIndex(
            model_name='pronunciationattempt',
            index=models.Index(fields=['user', 'created_at'], name='reading_pro_user_id_e99be6_idx'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('book', 'order'), name='unique_unit_order_per_book'),
        ),
        migrations.AddIndex(
            model_name='readinglesson',
            index=models.Index(fields=['unit', 'order'], name='reading_rea_unit_id_1f95d3_idx'),
        ),
        migrations.AddIndex(
            model_name='readinglesson',
            index=models.Index(fields=['created_at'], name='reading_rea_created_80672c_idx'),
        ),
        migrations.AddConstraint(
            model_name='readinglesson',
            constraint=models.UniqueConstraint(fields=('unit', 'order'), name='unique_lesson_order_per_unit'),
        ),
    ]
