# Generated by Django 5.2.11 on 2026-03-30 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0002_lessonprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total_attempts', models.PositiveIntegerField(default=0)),
                ('avg_score', models.FloatField(default=0)),
                ('lessons_completed', models.PositiveIntegerField(default=0)),
                ('total_practice_time', models.PositiveIntegerField(default=0)),
                ('words_practiced', models.JSONField(default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'date'], name='reading_use_user_id_065436_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='WordAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('total_attempts', models.PositiveIntegerField(default=0)),
                ('correct_attempts', models.PositiveIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='word_stats', to='reading.readinglesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-total_attempts'],
                'indexes': [models.Index(fields=['user', 'word'], name='reading_wor_user_id_bcc951_idx'), models.Index(fields=['user', '-total_attempts'], name='reading_wor_user_id_27334a_idx')],
                'unique_together': {('user', 'word', 'lesson')},
            },
        ),
    ]
